# installation: conda env create -f environment.yml
name: floral
channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.11.13
  - tqdm=4.67.1
  - matplotlib=3.10.3
  - omegaconf=2.3.0
  - twine=6.1.0
  - build=0.10.0
  - lightning=2.5.2
  - joblib=1.4.2
  - pip
  - pip:
    - torch==2.6.0
    - gpytorch==1.14
    - tensorboard==2.20.0
    - torchdiffeq==0.2.5
    - wandb==0.21.0
    - neuraloperator==1.0.2
