FLOREN:
  learning_rate: 0.001963
  batch_size: 256
  max_epochs: 10000
  optimizer: "AdamW"
  weight_decay: 0.00000187855043273742
  latent_dim: 20
  num_centers: 20
  time_embed_freq: 8
  scheduler: "exponential"
  exponential_scheduler_gamma: 0.99
  lr_scheduler_step: 5
  lr_scheduler_gamma: 0.1
