FLOREN:
  learning_rate: 5.0e-3
  batch_size: 512
  max_epochs: 5000
  optimizer: "Adam"
  weight_decay: 1.0e-4
  latent_dim: 35
  num_centers: 10
  time_embed_freq: 64
  scheduler: "exponential"
  exponential_scheduler_gamma: 0.99
  lr_scheduler_step: 5
  lr_scheduler_gamma: 0.1
