# Configutations for Darcy Flow

job_name: "Darcy_1000_samples_500_sensors" # Unique identifier for each run
mfFlow: True # True means residual operator is learned
checkpoint_save_path: "./experiments/Darcy/" # Save path for the checkpoints
checkpoint_load_path: Null # If provided, this checkpoint will be loaded
logger_name: "Darcy" # Logger folder

data:
  nx: 1 # Output field dimensionality
  nc: 4096 # Input field dimensionality
  nd: 2 # Domain dimensionality
  low_fidelity:
    path: "./low_fidelity.npz"
  high_fidelity:
    path: "./high_fidelity.npz"
    n_samples: 1000 #Number of samples of the data set to use
    n_sensors: 500 # Number of sensors in the output domain
  test_data_path: "./test_data.npz"

dataloader:
  reload: False # True: (Normalized) TensorDataset is reloaded; Must be true for train.state="eval"
  reload_sensors: False # If True, "sensor_location.pt" file will be used. If 'reload' is True, then it will reload anyways.
  batch_size: 256 # batch size
  train_ratio: 0.7 # percentage of {n_samples} to train
  num_workers: 6 # Number of workers
  normalize:
    field: True # Normalize the field for training
    condition: True # Normalize the conditon for trianing

train:
  stage: "train" # {train} : train the model; {eval} : Evaluate the model using provided checkpoint
  accelerator: 'gpu'
  devices: 4
  strategy: 'ddp'
  precision: 'bf16-mixed'
  max_epochs: 5000
  learning_rate: 5.0e-3
  weight_decay: 1.0e-4

flow:
  time_emb_freq: 4 # time embedding
  sig_min: 1.0e-5 # gaussian std for the data
  latent_dim: 35 # latent for the embedding (state and condition)
  num_centers: 10 # Number of RBF centers for domain embedding

generate:
  minibatch_size: 10 # number of domain points to process at a time (increase if memory is available)
  n_gen: 100 # number of samples generated (for UQ purposes)
  nT: 100 # number of time steps for integration

plot:
  visualize: False
  save: True
