# Configutations for Poisson Equation

data:
  path: null
  low_fidelity:
    n_pts: 5 # number of spatial points
    n_samples: 5000 # number of data samples
    checkpoint_path: "./experiments/mfFlow/Poisson/lowFidelity/checkpoints"
    logger_name: "poisson_low_fidelity"
  high_fidelity:
    n_pts: 100 # number of spatial points
    n_samples: 10000 # number of data samples
    checkpoint_path: "./experiments/mfFlow/Poisson/highFidelity/checkpoints"
    logger_name: "poisson_high_fidelity"

dataloader:
  batch_size: 512
  train_ratio: 0.7

train:
  accelerator: 'cpu'
  devices: 1
  strategy: 'ddp'
  precision: 'bf16-mixed'
  max_epochs: 1
  learning_rate: 1.0e-2
  weight_decay: 1.0e-4

flow:
  time_emb_freq: 4 # time embedding
  sig_min: 1.0e-5 # gaussian std for the data
  latent_dim: 40 # latent for the embedding (state and condition)

generate:
  n_samples: 1000 # number of input conditions simulated
  n_steps: 100 # number of time steps for integration

plot:
  visualize: False
  save: True
