# Configutations for Poisson Equation

data:
  corrFlow: True # if True then High fideltiy will use low fideltiy model
  low_fidelity:
    data_path: "./data/poisson/low_fidelity.npz"
  high_fidelity:
    data_path: "./data/poisson/high_fidelity.npz"
    checkpoint_save_path: "./experiments/Poisson/"
    checkpoint_load_path: "/home/sbhola/caslab/mfFlow/experiments/Poisson/corrFlow/model-epoch=3738-val_loss=0.19.ckpt"
    logger_name: "Poisson" # logger folder
    n_samples: 2000 # Number of samples of the data set to use

dataloader:
  batch_size: 512 # batch size
  train_ratio: 0.7 # percentage of {n_samples} to train

train:
  stage: "train" # {train} model trains the model, {eval} model evals the model
  accelerator: 'gpu'
  devices: 3
  strategy: 'ddp'
  precision: 'bf16-mixed'
  max_epochs: 5000
  learning_rate: 5.0e-3
  weight_decay: 1.0e-4

flow:
  time_emb_freq: 4 # time embedding
  sig_min: 1.0e-5 # gaussian std for the data
  latent_dim: 35 # latent for the embedding (state and condition)
  num_centers: 10 # Number of RBF centers for domain embedding

generate:
  n_gen: 200
  nT: 100 # number of time steps for integration

plot:
  visualize: False
  save: True
