# examples/oneDCorr/config_floral.yml
# configutations for 1-D toy problem

# general configuration
job_name: "oneDCorr_50_samples" # Unique identifier for each run
floral: True # True means residual operator is learned
tune_hyperparameters: False # If true, then hyperparameter sweep is conducted
checkpoint_save_path: "./experiments/oneDCorr/" # Save path for the checkpoints
checkpoint_load_path: Null # If provided, this checkpoint will be loaded
logger_name: "oneDCorr" # Logger folder

# configuration for data
data:
  n_samples: 50 # total samples for training + validation (for tractability)
  low_fidelity:
    path: "./low_fidelity.npz"
  high_fidelity:
    path: "./high_fidelity.npz"
  shape:
    field:
      dims: 1
      ch_in: 1
    condition:
      dims: 1
      ch_in: 1

# configuration for dataloader
dataloader:
  reload: False # True: (Normalized) TensorDataset is reloaded; Must be true for train.state="eval"
  train_ratio: 0.7 # percentage of {n_samples} to train
  num_workers: 6 # Number of workers
  normalize:
    # normalization: (x - mu) * sigma_t / sigma
    field:
      enabled: True # True: normalize the field
      auto: True # If True, mean and std are computed.
      mean: [0.1] # For example, [0.5] if want specified (per channel)
      std: [0.5] # For example, [0.5] if want specified (per channel)
    condition:
      enabled: True # True: normalize the field
      auto: True # If True, mean and std are computed.
      mean: [2.0] # For example, [0.5] if want specified (per channel)
      std: [3.5] # For example, [0.5] if want specified (per channel)

# configuration for training
train:
  stage: "train" # {train} : train the model; {eval} : Evaluate the model using provided checkpoint
  accelerator: 'gpu'
  devices: 4
  precision: '32-true'

# configuration for flow-matching
flow:
  sig_min: 1.0e-5 # gaussian std for the data
  field_sub_sample_factor: [2, 4, 5] # field_resolution / field_sub_sample_factor
  condition_sub_sample_factor: [2, 4, 5] # condition_resolution / condition_sub_sample_factor
  operator:
    field:
      ch_hidden: 32 # hidden channels in field operator
      n_modes: 32 # number of modes to keep in the field operator
    condition:
      ch_out: 16 # output channels for the condition operator
      ch_hidden: 32 # hidden channels in the condition operator
      n_modes: 32 # number of modes ot keep in the condition operator

# configuration for PDE solution generation
generate:
  minibatch_size: 10 # number of domain points to process at a time (increase if memory is available)
  n_gen: 5 # number of samples generated (for UQ purposes)
  nT: 10 # number of time steps for integration
  method: "dopri5" # method for ODE solver
  atol: 1.0e-4 # absolute tolerance for ODE solver
  rtol: 1.0e-4 # relative tolerance for ODE solver
