name: Lint and Format Python Code

on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Install dependencies
      run: pre-commit install

    - name: Run pre-commit
      run: pre-commit run --all-files
